README.md
=> Add bootstrapping information to the README

screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/ScreenManager.java, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/concrete/ConcreteScreen.java, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/first/FirstScreen.java, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/second/SecondScreen.java, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/second/SecondScreenPresenter.java, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/third/ThirdScreen.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcher.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/Screen.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenPopListener.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcher.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcherFactory.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcherState.java
=> Round out parameter checking

screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/Screen.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenPopListener.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcher.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcherFactory.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcherState.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenTransition.java
=> Add javadoc on all public methods

screen-switcher/build.gradle, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcherState.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherStateTest.java
=> Add tests for ScreenSwitcherState

screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcher.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcherFactory.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherFactoryTest.java
=> Add tests for ScreenSwitcherFactory

screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcherPushTest.java
=> Add tests for ActivityScreenSwitcher#push

screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/ScreenSwitcherApplication.java, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/concrete/ConcreteScreen.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcherState.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherStateTest.java
This also includes a change to ScreenSwitcherState to remove a leak.
Closes #22
=> Add lead canary to concrete screen

screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcher.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcherState.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcherPushTest.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcherTest.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherStateTest.java
=> Verify duplicate screens aren't allowed

screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcherPopTest.java
=> Test ActivityScreenSwitcher#pop

.travis.yml, build.gradle, screen-switcher-sample/build.gradle, screen-switcher-sample/src/androidTest/java/com/jaynewstrom/screenswitchersample/MainActivityTest.java
Closes #7 
This should round out the testing of existing code.
=> Test the sample

.travis.yml, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcherState.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherStateTest.java
=> Add #indexOf to ScreenSwitcherState

screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/ScreenManager.java, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/second/SecondScreen.java, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/third/ThirdView.java, screen-switcher-sample/src/main/res/layout/third_view.xml, screen-switcher-sample/src/main/res/values/strings.xml, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcherState.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherStateTest.java
This allows the use of something like ScreenManager#popTo.
References #6
=> Add ScreenSwitcherState#screenCount

gradle.properties, screen-switcher/build.gradle
This allows for `./gradlew install` to get the artifact installed in your local
maven repo
=> Add all information to eventually ship to bintray

screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/ScreenManager.java, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/first/FirstView.java, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/third/ThirdView.java, screen-switcher-sample/src/main/res/layout/first_view.xml, screen-switcher-sample/src/main/res/layout/third_view.xml, screen-switcher-sample/src/main/res/values/strings.xml, screen-switcher/build.gradle, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcher.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcher.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcherState.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/Utils.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcherReplaceScreensWithTest.java
Exception cases are tested, but functionality testing will be done in a
followup.
References #6
=> Add ScreenSwitcher#replaceScreensWith

screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcher.java
=> Remove for each loop syntax

screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcher.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcherPopTest.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcherPushTest.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcherReplaceScreensWithTest.java
Also add some tests around this functionality to prevent future regressions.
=> Fix a bug with transitioning

screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcher.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ActivityScreenSwitcherPopTest.java
This prevents a leak from occurring on rotation, as well as removing any
potential state issues.
=> Eagerly remove screens from state when popping

screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/RealScreenSwitcher.java
=> Ensure transition runnables are only executed once.

screen-switcher-sample/build.gradle, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/MainActivityModule.java, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/ScreenSwitcherApplication.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/RealScreenSwitcher.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenLifecycleListener.java, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcherState.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/AssertingScreenLifecycleListener.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherFactoryTest.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherPopTest.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherPushTest.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherReplaceScreensWithTest.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherStateTest.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherTest.java, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenTestUtils.java
=> Add a ScreenLifecycleListener

screen-switcher/build.gradle
=> Fix artifact id.

screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/RealScreenSwitcher.kt, screen-switcher/src/main/res/values/ids.xml
This is helpful in relation to #72
=> Add a tag to the view created by the screen containing the screen.

build.gradle, screen-switcher/build.gradle
I tried to work around a naming collision, but it turns out those files aren't needed.
=> Fix deployment/packaging.

build.gradle, gradle.properties, sample-core/build.gradle, sample-screen-first/build.gradle, sample-screen-second/build.gradle, sample-screen-third/build.gradle, screen-manager/build.gradle, screen-manager/src/main/java/com/jaynewstrom/screenswitcher/screenmanager/ScreenManager.kt, screen-switcher-sample/build.gradle, screen-switcher-sample/src/androidTest/java/com/jaynewstrom/screenswitchersample/activity/MainActivityTest.kt, screen-switcher/build.gradle, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/ScreenSwitcher.kt
=> Convert to AndroidX

sample-core/src/main/java/com/jaynewstrom/screenswitchersample/core/BaseScreen.kt, sample-core/src/main/java/com/jaynewstrom/screenswitchersample/core/ScreenParentComponent.kt, sample-screen-badge/src/main/java/com/jaynewstrom/screenswitchersample/badge/BadgeScreen.kt, sample-screen-color/src/main/java/com/jaynewstrom/screenswitchersample/color/ColorScreen.kt, sample-screen-first/src/main/java/com/jaynewstrom/screenswitchersample/first/FirstScreen.kt, sample-screen-second/src/main/java/com/jaynewstrom/screenswitchersample/second/SecondScreen.kt, sample-screen-third/src/main/java/com/jaynewstrom/screenswitchersample/third/ThirdScreen.kt, screen-switcher-sample/src/main/java/com/jaynewstrom/screenswitchersample/activity/MainActivityModule.kt, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/NoScreenFoundScreen.kt, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/RealScreenSwitcher.kt, screen-switcher/src/main/java/com/jaynewstrom/screenswitcher/Screen.kt, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenSwitcherTest.kt, screen-switcher/src/test/java/com/jaynewstrom/screenswitcher/ScreenTestUtils.kt, tab-bar/src/main/java/com/jaynewstrom/screenswitcher/tabbar/TabBarItem.kt, tab-bar/src/main/java/com/jaynewstrom/screenswitcher/tabbar/TabBarScreen.kt
=> Pass ScreenSwitcherState to Screen#createView.

build.gradle, sample-screen-first/src/main/res/layout/first_view.xml, sample-screen-second/src/main/res/layout/second_view.xml, screen-switcher-sample/build.gradle, screen-switcher-sample/src/androidTest/java/com/jaynewstrom/screenswitchersample/activity/MainActivityTest.kt, screen-switcher-sample/src/androidTest/java/com/jaynewstrom/screenswitchersample/activity/TextViewMatcher.kt
=> Add tests for tab bar and more advanced features such as state restoration.
